### ISSUE TITLE
Allow objects in the facade, not just functions

### ISSUE THREAD

**Issue by nicolassanmar** [garbles/react-facade#4]
I would like to separate hooks inside different categories, and I think it would be nice if we had the option to be able to define a facade like:
``` typescript
export type Hooks = {
  useHook1: typeof useHook1
  category: {
    useHook2: typeof useHook2
  }
}
```

Right now, the `createFacade` function leaves out every non function property.

I suggest that we should allow mocking everything, or at least objects. I don't see any issue allowing devs to mock non-functions as well. If someone for some reason wants to mock a string, I think we should not care.

I tried to edit the code myself but I don't really understand the comment that explains why there is a fallback function for this. Is this challenging to implement?

**Comment by ftzi** [comment]
Up! @garbles would that be a possibility?

**Comment by garbles** [comment]
Hey sorry! I somehow missed the email when this issue was opened so thanks for the bump. I'm on break now, so I'll take a look in the next few days.

**Comment by ftzi** [comment]
Great! Many thanks! 😄

**Comment by garbles** [comment]
Alright I just published `v0.4.0` which should resolve this. LMK!

**Comment by ftzi** [comment]
Hi @garbles! Merry Christmas and many thanks!

I have a specific use case where it doesn't work and I understand if it isn't feasible as it's problematic. I use [trpc](https://github.com/trpc/trpc), which usage I want is like the following: `hooks.trpc.a.b.c.myEndpoint.useQuery()`. The apparent issue is that `trpc` is already a proxy, so there is some kind of conflict with your implementation, which also uses a proxy. With the 0.4.0 change, the `trpc` type now shows to be used as there are some functions/hooks on its root.

With `hooks.trpc()...` I works since before but I don't like having to call it every time. As a possible solution, maybe we could have in this lib a function X (no idea how it could be called) that would just create a dummy class that you could check every root prop for `instanceof`, and if it's the case, it would use the given implementation without having to call it. The implementation could be something like `{ trpc: X(trpc) }`, X being just something like
```tsx
class classX {
  constructor(x) {
    return X
  }
};
const X = (x) => new classX(x)
```

I am not really sure how your implementation works as I haven't taken a long time to analyze it, but maybe it could just use normal objects instead of proxies to access the root props. With the Provider, we would just define the root object where the props are. `hooks` could be the result of [react-hooks-global-state](https://github.com/dai-shi/react-hooks-global-state), and the provider argument would set the global state with the initial value of the provider property.

**Comment by garbles** [comment]
@SrBrahma I'm happy to look into this, though I don't quite understand the problem. It would be super helpful if you made a demo repo (or a PR with a failing test).
