### ISSUE TITLE
What's the reason for wrapping it in a proxy?

### ISSUE THREAD

**Issue by donnyroufs** [garbles/react-facade#5]
I am having a hard time understanding what it solves / why it's needed. I would assume it has to do with preventing
re-renders?

**Comment by garbles** [comment]
Hello! I wrote a previous explanation but deleted it because I didn't think it answered your question.

The library's purpose is to make dependency injection easier. It's entirely possible to use a simple React context that does the same thing, but there's a lot of boiler plate. _If_ you wanted the same interface as this library, you might write something like this,

```ts
type Hooks = {
  useCurrentUser(): User;

  projects: {
    useOne(id: string): Project;
    useMany(): Project[];
  },

  // ... etc.
};

const HooksContext = React.createContext<Hooks | null>(null);

export const hooks: Hooks = {
  useCurrentUser() {
    const ctx = React.useContext(HooksContext);
    
    if (ctx === null) throw;

    return ctx.useCurrentUser();
  },

  projects: {
    useOne(id: string) {
      const ctx = React.useContext(HooksContext);

      if (ctx === null) throw;

      return ctx.projects.useProject(id);
    },

    useMany() {
      const ctx = React.useContext(HooksContext);

      if (ctx === null) throw;

      return ctx.projects.useMany();
    }
  },

  // ... etc.
};

export const ImplementationProvider = HooksContext.Provider;
```

The Proxy allows you to completely forgo the implementation of the `hooks` object while the type alias makes it appear as if there is a concrete implementation with specific key paths such as `hooks.project.useMany()` where everything type checks correctly.

Does this answer the question?
